# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/0rsk/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  git config --global user.email "server@0rsk.com"
  git config --global user.name "0rsk.com"
  pdd -f /dev/null
  /usr/bin/install-postgres.sh
  bundle install --no-color
merge:
  script: |-
    bundle exec rake
